"""Audit export pipeline tests (WO-0001): exporter, consumer, DDL.

The Restate admin HTTP surface is faked with httpx.MockTransport using the
exact request/response shapes observed on the live 1.7.10 cluster (POST
/query with Accept: application/json -> {"rows": [...]}, RFC3339 timestamp
strings); the Kafka producer/consumer are faked in memory. Production goes
through the same code paths against the real broker and admin API.
"""

from __future__ import annotations

import json
import re
from collections.abc import AsyncIterator
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import httpx
import pytest
import pytest_asyncio

from kernel.audit_export.consumer import AuditConsumer
from kernel.audit_export.exporter import (
    EVENT_TYPE,
    AuditExporter,
    build_event,
    upsert_audit_event,
)
from kernel.audit_export.restate_client import RestateAdminClient, parse_ts
from kernel.db import Database

REPO = Path(__file__).resolve().parent.parent

_FIXED_NOW = datetime(2026, 9, 17, 9, 0, 0, tzinfo=UTC)

# The cursor predicate generated by RestateAdminClient.fetch_invocations.
_CURSOR_RE = re.compile(
    r"WHERE created_at > TIMESTAMP '([^']+)' "
    r"OR \(created_at = TIMESTAMP '([^']+)' AND id > '([^']*)'\)"
)

_INVOCATIONS: list[dict[str, Any]] = [
    {
        "id": "inv_0001",
        "target": "executor/notify",
        "target_service_name": "executor",
        "target_handler_name": "notify",
        "status": "completed",
        "created_at": "2026-09-17T08:00:00.100Z",
        "modified_at": "2026-09-17T08:00:01.100Z",
        "invoked_by": "admin",
        "trace_id": "t1",
    },
    {
        "id": "inv_0002",
        "target": "executor/run",
        "target_service_name": "executor",
        "target_handler_name": "run",
        "status": "running",
        "created_at": "2026-09-17T08:00:00.500Z",
        "modified_at": "2026-09-17T08:00:02.500Z",
        "invoked_by": "gateway",
        "trace_id": "t2",
    },
    {
        # same millisecond as inv_0002: exercises the id tiebreaker
        "id": "inv_0003",
        "target": "reconciler/probe",
        "target_service_name": "reconciler",
        "target_handler_name": "probe",
        "status": "scheduled",
        "created_at": "2026-09-17T08:00:00.500Z",
        "modified_at": "2026-09-17T08:00:00.600Z",
        "invoked_by": "scheduler",
        "trace_id": "t3",
    },
]


def _row_key(row: dict[str, Any]) -> tuple[datetime, str]:
    ts = parse_ts(row["created_at"])
    assert ts is not None
    return ts, str(row["id"])


def _fake_restate_client(rows: list[dict[str, Any]]) -> httpx.AsyncClient:
    """MockTransport speaking the live admin /query protocol, including the
    cursor predicate semantics (strictly-after (created_at, id) ordering)."""

    def handler(request: httpx.Request) -> httpx.Response:
        assert request.url.path == "/query", "the live admin API has no other read path"
        assert request.headers.get("Accept") == "application/json"
        sql = json.loads(request.content.decode("utf-8"))["query"]
        selected = rows
        if m := _CURSOR_RE.search(sql):
            cursor = (datetime.fromisoformat(m.group(1)), m.group(3))
            selected = [r for r in rows if _row_key(r) > cursor]
        return httpx.Response(200, json={"rows": selected})

    return httpx.AsyncClient(transport=httpx.MockTransport(handler))


class FakePublisher:
    """In-memory audit event publisher (records every publish)."""

    def __init__(self) -> None:
        self.events: list[tuple[str, dict[str, Any]]] = []

    async def start(self) -> None: ...

    async def stop(self) -> None: ...

    async def publish(self, key: str, event: dict[str, Any]) -> None:
        self.events.append((key, event))


class FakeSource:
    """In-memory audit event source (drains a fixed event log)."""

    def __init__(self, events: list[dict[str, Any]]) -> None:
        self._pending = list(events)
        self.commits = 0

    async def start(self) -> None: ...

    async def stop(self) -> None: ...

    async def getmany(self, *, timeout_ms: int, max_records: int) -> list[dict[str, Any]]:
        del timeout_ms
        batch = self._pending[:max_records]
        del self._pending[:max_records]
        return batch

    async def commit(self) -> None:
        self.commits += 1


@pytest_asyncio.fixture
async def restate() -> AsyncIterator[httpx.AsyncClient]:
    client = _fake_restate_client(_INVOCATIONS)
    yield client
    await client.aclose()


def _exporter(db: Database, restate: httpx.AsyncClient, publisher: FakePublisher) -> AuditExporter:
    return AuditExporter(
        db,
        RestateAdminClient("http://restate.local", client=restate),
        publisher,
        exported_at_clock=lambda: _FIXED_NOW,
    )


async def _table_snapshot(db: Database) -> list[tuple[Any, ...]]:
    """Full-row projection of audit_events (asyncpg decodes timestamptz to
    UTC-aware datetimes, so values compare by instant, not by text)."""
    async with db.pool.acquire() as conn:
        rows = await conn.fetch(
            """SELECT invocation_id, service_name, handler_name, status,
                      created_at, raw::text, exported_at
               FROM audit_events ORDER BY invocation_id"""
        )
    return [tuple(r) for r in rows]


async def _reset(db: Database) -> None:
    async with db.pool.acquire() as conn:
        await conn.execute("TRUNCATE audit_events")
        await conn.execute(
            "UPDATE audit_export_state SET cursor_created_at = NULL, cursor_invocation_id = ''"
        )


# --------------------------------------------------------------------- DDL
async def test_ddl_applies_twice_idempotent(db: Database) -> None:
    """0004 must be re-runnable (apply_schema runs on every startup)."""
    sql = (REPO / "ops" / "sql" / "0004_audit_export.sql").read_text(encoding="utf-8")
    async with db.pool.acquire() as conn:
        await conn.execute(sql)  # 2nd application (db fixture already applied once)
        await conn.execute(sql)  # 3rd application
        singletons = await conn.fetchval("SELECT count(*) FROM audit_export_state")
        events = await conn.fetchval("SELECT count(*) FROM audit_events")
    assert singletons == 1, "singleton cursor row must never duplicate"
    assert events == 0


async def test_fresh_cursor_is_empty(db: Database) -> None:
    exporter = _exporter(db, _fake_restate_client([]), FakePublisher())
    assert await exporter.load_cursor() == (None, "")


# ----------------------------------------------------------------- exporter
async def test_exporter_exports_and_advances_cursor(
    db: Database, restate: httpx.AsyncClient
) -> None:
    await _reset(db)
    publisher = FakePublisher()
    exporter = _exporter(db, restate, publisher)

    assert await exporter.poll_once() == 3
    assert [key for key, _ in publisher.events] == ["inv_0001", "inv_0002", "inv_0003"]
    for key, event in publisher.events:
        assert event["event_type"] == EVENT_TYPE
        assert event["exported_at"] == _FIXED_NOW.isoformat()
        assert event["invocation"]["id"] == key

    snapshot = await _table_snapshot(db)
    assert len(snapshot) == 3
    assert snapshot[0][:4] == ("inv_0001", "executor", "notify", "completed")
    assert snapshot[1][:4] == ("inv_0002", "executor", "run", "running")
    assert snapshot[2][:4] == ("inv_0003", "reconciler", "probe", "scheduled")
    # created_at normalized from the Z-suffix strings to aware datetimes
    assert snapshot[0][4] == datetime(2026, 9, 17, 8, 0, 0, 100000, tzinfo=UTC)
    assert snapshot[0][6] == _FIXED_NOW

    # cursor advanced to (last created_at, last id) — same-ms tiebreaker held
    cursor_ts, cursor_id = await exporter.load_cursor()
    assert cursor_ts == datetime(2026, 9, 17, 8, 0, 0, 500000, tzinfo=UTC)
    assert cursor_id == "inv_0003"

    # second poll: the cursor predicate filters everything out
    assert await exporter.poll_once() == 0
    assert len(publisher.events) == 3


async def test_reexport_of_same_records_produces_no_duplicates(
    db: Database, restate: httpx.AsyncClient
) -> None:
    await _reset(db)
    publisher = FakePublisher()
    exporter = _exporter(db, restate, publisher)
    await exporter.poll_once()
    snapshot = await _table_snapshot(db)
    assert len(snapshot) == 3

    # simulate cursor loss (restored from an old backup): full re-export
    async with db.pool.acquire() as conn:
        await conn.execute(
            "UPDATE audit_export_state SET cursor_created_at = NULL, cursor_invocation_id = ''"
        )
    assert await exporter.poll_once() == 3
    assert len(publisher.events) == 6  # re-published to Kafka...
    assert await _table_snapshot(db) == snapshot  # ...but PG rows identical, no duplicates
    async with db.pool.acquire() as conn:
        count = await conn.fetchval("SELECT count(*) FROM audit_events")
    assert count == 3


# ----------------------------------------------------------------- consumer
async def test_consumer_replay_rebuilds_identical_table(
    db: Database, restate: httpx.AsyncClient
) -> None:
    await _reset(db)
    publisher = FakePublisher()
    await _exporter(db, restate, publisher).poll_once()
    original = await _table_snapshot(db)
    assert len(original) == 3

    # database lost; replay the published events from earliest offset
    async with db.pool.acquire() as conn:
        await conn.execute("TRUNCATE audit_events")
    source = FakeSource([event for _, event in publisher.events])
    consumer = AuditConsumer(db, source)
    assert await consumer.poll_once() == 3
    assert source.commits == 1, "offsets commit only after the batch applied"
    assert await _table_snapshot(db) == original

    # a full second replay (earliest offset again) is still idempotent
    replay = FakeSource([event for _, event in publisher.events])
    assert await AuditConsumer(db, replay).poll_once() == 3
    assert await _table_snapshot(db) == original


async def test_consumer_replay_all_drains_and_stops(db: Database) -> None:
    await _reset(db)
    events = [build_event(row, exported_at=_FIXED_NOW) for row in _INVOCATIONS[:2]]
    consumer = AuditConsumer(db, FakeSource(events))
    assert await consumer.replay_all(idle_rounds=2) == 2
    async with db.pool.acquire() as conn:
        count = await conn.fetchval("SELECT count(*) FROM audit_events")
    assert count == 2


# ----------------------------------------------------------------- payloads
async def test_upsert_rejects_event_without_invocation_id(db: Database) -> None:
    with pytest.raises(ValueError, match="invocation id"):
        await upsert_audit_event(db, {"event_type": EVENT_TYPE, "invocation": {}})


def test_parse_ts_shapes() -> None:
    assert parse_ts("2026-09-17T08:00:00.123Z") == datetime(
        2026, 9, 17, 8, 0, 0, 123000, tzinfo=UTC
    )
    assert parse_ts("2026-09-17 08:00:00+00:00") == datetime(2026, 9, 17, 8, tzinfo=UTC)
    assert parse_ts(0) == datetime(1970, 1, 1, tzinfo=UTC)
    assert parse_ts(86400000) == datetime(1970, 1, 2, tzinfo=UTC)
    assert parse_ts(None) is None
    with pytest.raises(ValueError, match="unparseable"):
        parse_ts(object())
